import type { Metadata } from "next";
import { Noto_Sans } from "@next/font/google"; // Menggunakan Noto Sans
import "./globals.css";

export const metadata: Metadata = {
  title: "Isa Medika Persada",
  description: "Generated by create next app",
};

const notoSansFont = Noto_Sans({
  subsets: ["latin"],
  variable: "--font-noto-sans",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link rel="icon" href="/logo.svg" type="image/svg+xml" />{" "}
      </head>

      <body className={`${notoSansFont.variable} antialiased`}>{children}</body>
    </html>
  );
}
